name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate APP_KEY
      run: php artisan key:generate

    - name: Run Laravel Tests
      run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/ # Ganti sesuai direktori Laravel di hosting kamu
        local-dir: ./ # Bisa sesuaikan kalau hanya ingin deploy folder tertentu


