name: Laravel CI/CD

on:
  push:
    branches: [ main ]     # Trigger otomatis kalau ada push ke main
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'                # Versi PHP, sesuaikan jika perlu
        extensions: mbstring, bcmath, pdo_mysql, zip

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-interaction

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run tests
      run: ./vendor/bin/phpunit
