name: Laravel CI/CD Delivery Only

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate APP_KEY
      run: php artisan key:generate

    - name: Run Laravel Tests
      run: php artisan test

  zip:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install zip -y

    - name: Create zip file
      run: |
        zip -r laravel-artifact.zip . -x ".git/*" "vendor/*" "node_modules/*" ".github/*"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: laravel-artifact
        path: laravel-artifact.zip

